### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by stoivo** [facelessuser/ThemeTweaker#3]
I have trouble getting started. I would like to try this tool, but I can not get started? 
What do I have to do to get started?

I start with running: Theme Tweaker: Toggle Tweak Mode

and than what do I do?

platform: OSX 10.10
Build 3083

**Comment by facelessuser** [comment]
You can read about it here http://facelessuser.github.io/ThemeTweaker/usage/#constructing-commands.

It's basically a number of commands that can tweak your color scheme .  There is also an example keymap file here https://github.com/facelessuser/ThemeTweaker/blob/master/example.sublime-keymap.

It was more of a fun project little project.  I'm not sure how many practical uses for it there are, but its nifty if you just want to make some adjustments to a theme.  I also use it in https://github.com/facelessuser/ThemeScheduler to allow you to lighten or darken a theme or apply other filters at certain times of the day.

**Comment by stoivo** [comment]
:+1:
